mine "C:/workspace/CSharp/VsProjects/gurosilang/lib/core.grsl";

module Hangman;
shorten Hangman;
shorten std;
shorten collections;
shorten meta;

memsize 1920;

run
{
    let c: MyClass = new MyClass();
    c.getMsg();
}


how void func(value: List<string>)
{
}

how void debug(value: any)
{
    Log.println(str(value));
}

class MyClass: public
{
    
    field private _msg: string;

    how string getMsg(): public
    {
        return "Hello world";
    }
}